name: kliv_app
description: Application mobile KLIV
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # âœ… Pour les localisations (DatePicker, formats FR)
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  url_launcher: ^6.3.0
  shimmer: ^3.0.0

  # State management
  provider: ^6.1.2
  table_calendar: ^3.0.9

  # Notifications & calendrier
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.0

  # HTTP
  http: ^1.1.0
  dio: ^5.4.0

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  path_provider: ^2.0.14
  excel: ^2.0.0
  permission_handler: ^11.0.0
  device_info_plus: ^10.1.0
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2

  # Utils
  intl: ^0.20.2

  # Graphiques
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icons/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_foreground: "assets/icon.png"